import 'package:flutter/material.dart';

import './models/category.dart';
import './models/silverpiece.dart';

const DUMMY_CATEGORIES = const [
  Category(
    id: 'WN',
    title: 'Women\'s Necklaces',
    color: Colors.purple,
    img: 'assets/images/8.png',
  ),
  Category(
    id: 'MN',
    title: 'Men\'s Necklaces',
    color: Colors.red,
    img: 'assets/images/13.jpg',
  ),
  Category(
    id: 'WB',
    title: 'Women\'s Bracelets',
    color: Colors.orange,
    img: 'assets/images/3.png',
  ),
  Category(
    id: 'MB',
    title: 'Men\'s Bracelets',
    color: Colors.amber,
    img: 'assets/images/12.jpg',
  ),
  Category(
    id: 'WR',
    title: 'Women\'s Rings',
    color: Colors.blue,
    img: 'assets/images/11.jpg',
  ),
  Category(
    id: 'MR',
    title: 'Men\'s Rings',
    color: Colors.green,
    img: 'assets/images/sultan.jpg',
  ),
  Category(
    id: 'HM',
    title: 'Hand Made',
    color: Colors.lightBlue,
    img: 'assets/images/9.jpg',
  ),
  Category(
    id: 'A',
    title: 'anklets',
    color: Colors.lightGreen,
    img: 'assets/images/10.jpg',
  ),
  Category(
    id: 'E',
    title: 'Earrings',
    color: Colors.pink,
    img: 'assets/images/5.png',
  ),
  Category(
    id: 'NC',
    title: 'New Collections',
    color: Colors.teal,
    img: 'assets/images/3.png',
  ),
];

const DUMMY_SILVER_PIECES = const [
  SilverPiece(
      id: 'WN1',
      title: 'Red Necklace',
      categories: ['NC', 'WN'],
      gender: Gender.Female,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/7.png',
      icon_isAvailible: Icon(Icons.delete),
      price: '300',
      notavialableSizes: ['18', '19']),
  SilverPiece(
      id: 'WN2',
      title: 'Sunflower Necklace',
      categories: ['NC', 'WN'],
      gender: Gender.Female,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/sun.jpg',
      icon_isAvailible: Icon(Icons.delete),
      price: '195',
      notavialableSizes: ['18', '19']),
  SilverPiece(
      id: 'WN3',
      title: 'Mum Necklace',
      categories: ['NC', 'WN','MN'],
      gender: Gender.Both,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/13.jpg',
      icon_isAvailible: Icon(Icons.delete),
      price: '175',
      notavialableSizes: ['18', '19']),
  SilverPiece(
      id: 'WN4',
      title: 'Allah Necklace',
      categories: ['NC', 'WN'],
      gender: Gender.Female,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/allah.jpg',
      icon_isAvailible: Icon(Icons.delete),
      price: '250',
      notavialableSizes: ['18', '19']),
  SilverPiece(
      id: 'WN5',
      title: 'Mickey Necklace',
      categories: ['NC', 'WN'],
      gender: Gender.Female,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/mickey.jpg',
      icon_isAvailible: Icon(Icons.delete),
      price: '175',
      notavialableSizes: ['18', '19']),
  SilverPiece(
      id: 'WN6',
      title: 'Blue Necklace',
      categories: ['NC', 'WN'],
      gender: Gender.Female,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/blue_neck.jpg',
      icon_isAvailible: Icon(Icons.delete),
      price: '235',
      notavialableSizes: ['18', '19']),
  SilverPiece(
      id: 'WN7',
      title: 'Duck Necklace',
      categories: ['NC', 'WN'],
      gender: Gender.Female,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/duck.jpg',
      icon_isAvailible: Icon(Icons.delete),
      price: '200',
      notavialableSizes: ['18', '19']),
  SilverPiece(
      id: 'WN8',
      title: 'Moon Necklace',
      categories: ['NC', 'WN', 'MN'],
      gender: Gender.Both,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/helal.jpg',
      icon_isAvailible: Icon(Icons.delete),
      price: '150',
      notavialableSizes: ['18', '19']),
  SilverPiece(
      id: 'WN9',
      title: 'Fly Necklace',
      categories: ['NC', 'WN'],
      gender: Gender.Female,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/fly.jpg',
      icon_isAvailible: Icon(Icons.delete),
      price: '200',
      notavialableSizes: ['18', '19']),
  SilverPiece(
      id: 'MR1',
      title: 'El Sultan Ring',
      categories: ['MR'],
      gender: Gender.Male,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/sultan.jpg',
      icon_isAvailible: Icon(Icons.delete),
      price: '200',
      notavialableSizes: ['18', '19']),
  SilverPiece(
      id: 'MR2',
      title: 'El King Ring',
      categories: ['MR'],
      gender: Gender.Male,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/1.jpg',
      icon_isAvailible: Icon(Icons.delete),
      price: '200',
      notavialableSizes: ['18', '19']),
  SilverPiece(
      id: 'MR3',
      title: 'Sulitaire Ring',
      categories: ['MR'],
      gender: Gender.Male,
      avialableSizes: ['Sizes', '17', '18', '19', '20' , '21'],
      isAvailible: true,
      img: 'assets/images/4.png',
      icon_isAvailible: Icon(Icons.delete),
      price: '200',
      notavialableSizes: ['17', '21']),
       SilverPiece(
      id: 'WB1',
      title: 'Word Braclete',
      categories: ['NC', 'WB' , 'MB'],
      gender: Gender.Both,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/12.jpg',
      icon_isAvailible: Icon(Icons.delete),
      price: '200',
      notavialableSizes: ['18', '19']),
       SilverPiece(
      id: 'WB3',
      title: 'Jewllery Braclete',
      categories: ['NC', 'WB' ],
      gender: Gender.Female,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/3.png',
      icon_isAvailible: Icon(Icons.delete),
      price: '200',
      notavialableSizes: ['18', '19']),
      SilverPiece(
      id: 'WR1',
      title: 'Debla Ring',
      categories: ['NC', 'WR'],
      gender: Gender.Female,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/11.jpg',
      icon_isAvailible: Icon(Icons.delete),
      price: '200',
      notavialableSizes: ['18', '19']),
      SilverPiece(
      id: 'WR2',
      title: 'Twinz Ring',
      categories: ['NC', 'WR'],
      gender: Gender.Female,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/2.png',
      icon_isAvailible: Icon(Icons.delete),
      price: '200',
      notavialableSizes: ['18', '19']),
      SilverPiece(
      id: 'HM1',
      title: 'Gharaboly Name',
      categories: ['NC', 'HM'],
      gender: Gender.Both,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/9.jpg',
      icon_isAvailible: Icon(Icons.delete),
      price: '200',
      notavialableSizes: ['18', '19']),
      SilverPiece(
      id: 'A1',
      title: 'Anckel',
      categories: ['NC', 'A'],
      gender: Gender.Female,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/10.jpg',
      icon_isAvailible: Icon(Icons.delete),
      price: '200',
      notavialableSizes: ['18', '19']),
      SilverPiece(
      id: 'E1',
      title: 'Spider Earing ',
      categories: ['NC', 'E'],
      gender: Gender.Female,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/5.png',
      icon_isAvailible: Icon(Icons.delete),
      price: '200',
      notavialableSizes: ['18', '19']),
      SilverPiece(
      id: 'E2',
      title: 'Leaf Earing ',
      categories: ['NC', 'E'],
      gender: Gender.Female,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/6.png',
      icon_isAvailible: Icon(Icons.delete),
      price: '200',
      notavialableSizes: ['18', '19']),
      
      
];
