import 'package:flutter/material.dart';

import './models/category.dart';
import './models/silverpiece.dart';

const DUMMY_CATEGORIES = const [
  Category(
    id: 'WN',
    title: 'Women\'s Necklaces',
    color: Colors.purple,
    img: 'assets/images/8.png',
  ),
  Category(
    id: 'MN',
    title: 'Men\'s Necklaces',
    color: Colors.red,
    img: 'assets/images/13.jpg',
  ),
  Category(
    id: 'WB',
    title: 'Women\'s Bracelets',
    color: Colors.orange,
    img: 'assets/images/3.png',
  ),
  Category(
    id: 'MB',
    title: 'Men\'s Bracelets',
    color: Colors.amber,
    img: 'assets/images/12.jpg',
  ),
  Category(
    id: 'WR',
    title: 'Women\'s Rings',
    color: Colors.blue,
    img: 'assets/images/11.jpg',
  ),
  Category(
    id: 'MR',
    title: 'Men\'s Rings',
    color: Colors.green,
    img: 'assets/images/sultan.jpg',
  ),
  Category(
    id: 'HM',
    title: 'Hand Made',
    color: Colors.lightBlue,
    img: 'assets/images/9.jpg',
  ),
  Category(
    id: 'A',
    title: 'anklets',
    color: Colors.lightGreen,
    img: 'assets/images/10.jpg',
  ),
  Category(
    id: 'E',
    title: 'Earrings',
    color: Colors.pink,
    img: 'assets/images/5.png',
  ),
  Category(
    id: 'NC',
    title: 'New Collections',
    color: Colors.teal,
    img: 'assets/images/3.png',
  ),
];

const DUMMY_SILVER_PIECES = const [
  SilverPiece(
      id: 'WN1',
      title: 'Red Necklace',
      categories: ['NC', 'WN'],
      gender: Gender.Female,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/7.png',
      icon_isAvailible: Icon(Icons.delete),
      price: '300',
      notavialableSizes: ['18', '19']),
  SilverPiece(
      id: 'WN2',
      title: 'Sunflower Necklace',
      categories: ['NC', 'WN'],
      gender: Gender.Female,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/sun.jpg',
      icon_isAvailible: Icon(Icons.delete),
      price: '195',
      notavialableSizes: ['18', '19']),
  SilverPiece(
      id: 'WN3',
      title: 'Mum Necklace',
      categories: ['NC', 'WN'],
      gender: Gender.Both,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/13.jpg',
      icon_isAvailible: Icon(Icons.delete),
      price: '175',
      notavialableSizes: ['18', '19']),
  SilverPiece(
      id: 'WN4',
      title: 'Allah Necklace',
      categories: ['NC', 'WN'],
      gender: Gender.Female,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/allah.jpg',
      icon_isAvailible: Icon(Icons.delete),
      price: '250',
      notavialableSizes: ['18', '19']),
  SilverPiece(
      id: 'WN5',
      title: 'Mickey Necklace',
      categories: ['NC', 'WN'],
      gender: Gender.Female,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/mickey.jpg',
      icon_isAvailible: Icon(Icons.delete),
      price: '175',
      notavialableSizes: ['18', '19']),
  SilverPiece(
      id: 'WN6',
      title: 'Blue Necklace',
      categories: ['NC', 'WN'],
      gender: Gender.Female,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/blue_neck.jpg',
      icon_isAvailible: Icon(Icons.delete),
      price: '235',
      notavialableSizes: ['18', '19']),
  SilverPiece(
      id: 'WN7',
      title: 'Duck Necklace',
      categories: ['NC', 'WN'],
      gender: Gender.Female,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/duck.jpg',
      icon_isAvailible: Icon(Icons.delete),
      price: '200',
      notavialableSizes: ['18', '19']),
  SilverPiece(
      id: 'WN8',
      title: 'Moon Necklace',
      categories: ['NC', 'WN'],
      gender: Gender.Both,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: true,
      img: 'assets/images/helal.jpg',
      icon_isAvailible: Icon(Icons.delete),
      price: '150',
      notavialableSizes: ['18', '19']),
  SilverPiece(
      id: 'WN9',
      title: 'Fly Necklace',
      categories: ['NC', 'WN'],
      gender: Gender.Female,
      avialableSizes: ['Sizes', '17', '18', '19', '20'],
      isAvailible: false,
      img: 'assets/images/fly.jpg',
      icon_isAvailible: Icon(Icons.delete),
      price: '200',
      notavialableSizes: ['18', '19']),

];
